name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  release:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate trace_processor_shell
        shell: bash
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./build-trace-processor-shell.sh
      - name: Generate Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: False
          generate_release_notes: True
          fail_on_unmatched_files: True
          files: |
            build/trace_processor_shell.*
